### ISSUE TITLE
BUG: My NINEBOT E2 cant downgrade DRV and install SHFW

### ISSUE THREAD

**Issue by Alinus187** [scooterhacking/scooterhacking-issues-public#101]
### Scooterhacking Tool

Utility (SHUT)

### Type of issue

Other

### Severity of issue

medium (affects usability but has a workaround)

### SHUT Version

none

### SHFW Version

none 

### Scooter model

Ninebot Es2, Es3, Es4

### Description of the Bug

my scoter E2 cant downgrade DRV and install SHFW please help

### Steps to Reproduce

1 install ScooterHaking Utility 2 select my scooter 3 go to flash   3 press install/update SHFW (does not work) or attemp DRV downgrade(does not work as well

### Expected vs. Actual Behavior

I wish that this problem can be fixed

### Contact Information

totalin.

**Comment by Nyami11** [comment]
It's not a bug. Ninebot E2 series isn't supported by SHFW, ans probably never will be.

**Comment by paulederbaus** [comment]
Please send a screenshot of the info tab, but I guess Nyami is right

**Comment by paulederbaus** [comment]
No answer within 2 months
