### ISSUE TITLE
BUG: The wrong tire size is "recommended" for G2

### ISSUE THREAD

**Issue by TheRemyV** [scooterhacking/scooterhacking-issues-public#112]
### Scooterhacking Tool

Utility (SHUT)

### Type of issue

Other

### Severity of issue

low (asthetic, minor issue)

### SHUT Version

SHUT 2.6.1 (72)

### SHFW Version

SHFW 3.9.1

### Scooter model

Ninebot G2

### Description of the Bug

The info textbox for wheel size setting says that the default Wheel size for the Max G2 is just 8 inch. 
![Screenshot_20240907_063211_ScooterHacking Utility](https://github.com/user-attachments/assets/a6935e62-9e54-4ab9-adff-8c5c52980886)

### Steps to Reproduce

Go to the wheel size settings and tap on the "i"

### Expected vs. Actual Behavior

It doesn't bother me. I just noticed it by chance. However, it could be that someone else believes that and then really sets it to 8"

### Contact Information

TheRemy

**Comment by lekrsu** [comment]
This is/will be fixed on the upcoming Utility build on all supported models.
