### ISSUE TITLE
BUG: Pro2 wheel size speed calculation deviation increased

### ISSUE THREAD

**Issue by Z1mmb0** [scooterhacking/scooterhacking-issues-public#116]
### Scooterhacking Tool

Firmware (SHFW)

### Type of issue

UI / UX fix

### Severity of issue

medium (affects usability but has a workaround)

### SHUT Version

2.6.x

### SHFW Version

3.9.1

### Scooter model

Xiaomi Pro, Pro2, 1s, essential, 3

### Description of the Bug

wheel size parameter doesnt correlate with actual speeds. with shfw 3.9.1 the discrepancy increased. 
Originally noticed with shfw 3.7.x -> decreased wheel size to 8.3" to match speeds. 
Now with 3.9.1 8.3" is again 2-3kph off which lead to wheel size decresing to 8.1"

references: gps data recorded with 'm365dashboard' and radar station. 

tested tire: 8.5*3 (non OEM)

### Steps to Reproduce

1. Use a 8.5*3 tire (verification with oem tire needed)
2. set wheel size
3. record ride on flat terrain with 'm365dashboard' 
4. compare speed to gps data

### Expected vs. Actual Behavior

expected: 
speed should somewhat match when wheel size is set to 8.5"

actual: 
further deviation from previously set 8.3" leads to 8.0-8.1" wheel size parameter

### Contact Information

disc: zimmbo

**Comment by paulederbaus** [comment]
This is not firmware related. The calculation hasn't changed since 2.x. Please check your tires, your pressure and your weight.
