### ISSUE TITLE
BUG: Field Weakening not as strong

### ISSUE THREAD

**Issue by ahaas25** [scooterhacking/scooterhacking-issues-public#121]
### Scooterhacking Tool

Utility (SHUT)

### Type of issue

Performance Issue

### Severity of issue

medium (affects usability but has a workaround)

### SHUT Version

2.6.1

### SHFW Version

Regular-Base255-v3.10.0_v2_11

### Scooter model

Ninebot Es2, Es3, Es4

### Description of the Bug

Field weakening only accelerates me to 35 kph on flat ground. On SHFW v0.3.6 I was able to accelerate to 43 kph. Free spinning my scooter wheel also only gets 35 kph, whereas on SHFW v0.3.6 it could get up to 50 kph. I made sure there is no speed limit enabled in the SHFW.

### Steps to Reproduce

1. Enable field weakening
2. Configure it
3. Ride scooter at full throttle -> get to 43kph eventually

### Expected vs. Actual Behavior

1. Enable field weakening
2. Configure it
3. Ride scooter at full throttle -> get to 35kph and feel scooter cut power

### Contact Information

Poe

**Comment by Z1mmb0** [comment]
reset your parameters, reinitialize and try again

**Comment by ahaas25** [comment]
Tried this, no luck. Seems like field weakening is not as strong. Scooter barely gets to 35kph and any incline slows it down. Whereas before it could handle 35kph up moderate inclines

**Comment by lekrsu** [comment]
Look over your settings or link them here.

**Comment by ahaas25** [comment]
![Screenshot_20240921-223754](https://github.com/user-attachments/assets/f97557dc-b362-4b8b-86e7-b72f23bb0db3)
Here are my settings. Setting the max amperage to 15A didn't help either. I can feel field weakening kick in around ~32kph, but at ~33kph I feel the scooter cut power like a speed limit. I have the speed limit set to 100 KPH.

**Comment by Nyami11** [comment]
Turn on expert view at the top, set initial to 0 and variable current to 1000. Also if you just set speed limit to 0, it turns it off...

**Comment by ahaas25** [comment]
That's my bad, that fixed it!
