### ISSUE TITLE
BUG: Speed limit setting is not working with high performance settings on G2

### ISSUE THREAD

**Issue by Umba-SHU** [scooterhacking/scooterhacking-issues-public#126]
### Scooterhacking Tool

Firmware (SHFW)

### Type of issue

Performance issue

### Severity of issue

medium (affects usability but has a workaround)

### SHUT Version

SHUT 2.6.1

### SHFW Version

Regular-Base170-v3.9.1

### Scooter model

Ninebot G2

### Description of the Bug

BUG: Speed limit setting is not working with high performance settings on G2

### Steps to Reproduce

1. Set speed limit, e.g. 45 km/h
2. Enable Field Weakening with settings like in the screenshots (or any higher performance settings than these) 
3. Enable PMI Overmodulation 
4. Enable Zero Start
5. Put rear wheel in the air and press accelerator 

The wheel spins up so fast that it goes far beyond speed limiter setting and keeps spinning at that speed while accelerator remains pressed,  

PS Have tested this only with "wheel in the air" can't confirm it still happens with load. But assuming the limit should be applied in both cases. 
![WhatsApp Image 2024-10-08 at 12 37 42 (1)](https://github.com/user-attachments/assets/e5c4c743-8981-40b4-930b-56de681e0343)
![WhatsApp Image 2024-10-08 at 12 37 42](https://github.com/user-attachments/assets/ddee61d2-f559-42da-b057-3082ce639780)

### Expected vs. Actual Behavior

Expected: Set speed limit setting should override the acceleration speed at all times.
Actual behavior: Speed limiter not applied.

Workardound: at more mild settings of FW the speed limiter is working. It seems that the motor surpasses the speed barrier (with high performance settings) so fast that the speed limiter fails to register the barrier it is set to, and is not applied at all then. 

### Contact Information

@ilyasamui

**Comment by le3tspeak** [comment]
With FWK ON you should not accelerate in the air, as it is possible to damage the ESC by accelerating in the air. The speed limiter works normally on the ground with resistance.

**Comment by lekrsu** [comment]
You don't use field weakening in-air on any system.

**Comment by Umba-SHU** [comment]
> You don't use field weakening in-air on any system.

Thanks and good to know. I am not sure I have seen the warning not to try it in-air in the app

**Comment by Umba-SHU** [comment]
Thanks maybe worth adding this warning to the SHU in the  (i) section for FW option
