### ISSUE TITLE
BUG: Segway Ninebot kickscooter E2 Pro doesn't show up while searching for devices in scooterhackingutility

### ISSUE THREAD

**Issue by VKornel1031** [scooterhacking/scooterhacking-issues-public#132]
### Scooterhacking Tool

Utility (SHUT)

### Type of issue

Other

### Severity of issue

high (major functionality broken, no workaround)

### SHUT Version

I don't know

### SHFW Version

i don't know

### Scooter model

Ninebot Es2, Es3, Es4

### Description of the Bug

Scooter hacking utility says its supported but doesn't show up. Sorry if somebody already asked this.

### Steps to Reproduce

Open the app and try to find the Ninebot E2 Pro

### Expected vs. Actual Behavior

I expected it to show my scooter. Actual behavior it didn't show my scooter.

### Contact Information

@vkornel103120 on discord

**Comment by lekrsu** [comment]
E2 Pro, E2 Plus and E2 is not supported and is not a part of E2x series.
