### ISSUE TITLE
Rework of the current display on dash

### ISSUE THREAD

**Issue by PureComedi** [scooterhacking/scooterhacking-issues-public#41]
### Scooterhacking Tool

Firmware (SHFW)

### Type of feature

UI / UX

### Priority

medium (upcoming releases)

### SHUT Version

2.3.2

### SHFW Version

SHFW 0.3.7

### Scooter model

Mi Essential

### Description of the new feature

***(User Interface tab)***

Replace the current version of displaying motor amperage, which was mapping a percentage from 0A to the maximum that is set in your motor curve, all on the battery.

Instead use the BMS output, display it on the dash itself as a value, if needed, with a lower update frequency to lessen the UART spam

### Contact Information

discord : purecomedi

**Comment by paulederbaus** [comment]
feature implemented - will be available with prerelease 0.3.7 v7
