### ISSUE TITLE
Cruise control kick in only after 50% throttle. M365 regular latest shfw 

### ISSUE THREAD

**Issue by AlexS-hub** [scooterhacking/scooterhacking-issues-public#44]
### Scooterhacking Tool

Firmware (SHFW)

### Type of issue

Performance issue

### Severity of issue

high (major functionality broken, no workaround)

### SHUT Version

2.3.2

### SHFW Version

0.3.6

### Scooter model

Xiaomi M365

### Description of the Bug

All modes of cruise control activate only with 50% throttle or more.

### Steps to Reproduce

Turn on scooter apply 30 throttle, no cruise control

### Expected vs. Actual Behavior

Cruise control kicks in, it doesn't

### Contact Information

artemlitovskikh27@yandex.ru

**Comment by Nyami11** [comment]
> Scooter model
Xiaomi M365

Bit more context? Xiaomi M365 isn't even supported natively my SHFW. Do you have a 4-dot dash with a modified BLE firmware, a pro 1, or some other model's dash?

> Steps to Reproduce
Turn on scooter apply 30 throttle, no cruise control

What does "apply 30 throttle" even means?

> Expected vs. Actual Behavior
Cruise control kicks in, it doesn't

You mean, it activates, but doesn't give power?
There is a well known bug with cruise control, that sometimes (especially if you have a phone connected to it) it activates but doesn't give any power, so you have to turn it off, and re-enable it.

**Comment by paulederbaus** [comment]
How are you using cruise control?

If you use time, the throttle value needs to be above the min value of hall sensor settings. Here the speed change is also checked. The speed needs to be steady to enable cc.

If you are using single / double tap, the value is hardcoded to 100. This means it depends on your throttle. With a good working throttle, this should be around 40%.
(A good working throttle goes from 40 to 190.)

**Comment by AlexS-hub** [comment]
I use time mode. With cfw it works like a charm at about 15% -100%.  But with shfw cc only start from 50% -100%. I am sticking with cfw for now until it get fixed. 14:59, 21 февраля 2024 г., paulederbaus ***@***.***>:
How are you using cruise control?
If you use time, the throttle value needs to be above the min value of hall sensor settings.
If you are using single / double tap, the value is hardcoded to 100. This means it depends on your throttle. With a good working throttle, this should be around 40%.
(A good working throttle goes from 40 to 190.)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by AlexS-hub** [comment]
Power based cc also has 50%-100% throttle activation range. I use pro for 4 dot ble from telegram shfw official channel.

**Comment by paulederbaus** [comment]
If you dm me your uid via discord (paulederbaus), I can assign you an improved version.

**Comment by AlexS-hub** [comment]
> If you dm me your uid via discord (paulederbaus), I can assign you an improved version.

You mean that you have ble that works correctly?

**Comment by lekrsu** [comment]
> > If you dm me your uid via discord (paulederbaus), I can assign you an improved version.
> 
> You mean that you have ble that works correctly?

Why are we mixing BLE into this now?

**Comment by paulederbaus** [comment]
Issue closed - small adjustment of throttle diff and speed diff per loop

**Comment by AlexS-hub** [comment]
> Issue closed - small adjustment of throttle diff and speed diff per loop

It means i can flash shfw now and it will work like it should?
