### ISSUE TITLE
BUG: Odometer frozen on SHFW on Ninebot E22

### ISSUE THREAD

**Issue by ahaas25** [scooterhacking/scooterhacking-issues-public#46]
### Scooterhacking Tool

Utility (SHUT)

### Type of issue

UI / UX fix

### Severity of issue

low (asthetic, minor issue)

### SHUT Version

2.3.2

### SHFW Version

SHFW v0.3.6

### Scooter model

Ninebot E20, E25, E45

### Description of the Bug

Odometer does not update when using Nine Dash. Tested riding around 1 KM (through GPS) and then re-opened Nine Dash. Scooter reported exact same mileage. Reverting back to stock firmware allows the odometer to keep counting up, but does not account for miles ridden on the SHFW

### Steps to Reproduce

1. Flash latest SHFW
2. Ride scooter around at least 0.1 km
3. Check Ninebot Dashboard

### Expected vs. Actual Behavior

Expected: 500 KM on Odometer -> Ride 1 KM -> 501 KM on Odometer
Actual: 500 KM on Odometer -> Ride 1 KM -> 500 KM on Odometer

**Comment by paulederbaus** [comment]
Could you please attach a screenshot of the value you are talking about?

**Comment by ahaas25** [comment]
![Screenshot_20240301-170757](https://github.com/scooterhacking/scooterhacking-issues-public/assets/94150901/560f1ea0-2f7d-44c7-a1c3-f70d8e0576a0)
It's the same using both Nine Dash and Scootbatt

**Comment by paulederbaus** [comment]
I think I found the bug. Are you willing to test the fix? If yes, please contact me via Discord.

**Comment by ahaas25** [comment]
Contacted you on Discord.
