### ISSUE TITLE
Manual curve building keyboard bug

### ISSUE THREAD

**Issue by Nyami11** [scooterhacking/scooterhacking-issues-public#49]
### Scooterhacking Tool

Utility (SHUT)

### Type of issue

UI / UX fix

### Severity of issue

low (asthetic, minor issue)

### SHUT Version

Both public and prerelease

### SHFW Version

0.3.6

### Scooter model

Ninebot G30

### Description of the Bug

If you press the right or left key buttons the keyboard closes, if you press the Done button on the keyboard, it scrolls down to the bottom of the config tab and switches the keyboard to the text input keyboard

https://github.com/scooterhacking/scooterhacking-issues-public/assets/116882110/637a984d-889c-4c28-9c58-557e55a4f5fa

### Steps to Reproduce

1. Switch to manual curve building mode
2. Press the textbox so the keyboars shows up
3. If you press the right or left key buttons the keyboard closes, if you press the Done button on the keyboard, it scrolls down to the bottom of the config tab and switches the keyboard to the text input keyboard

### Expected vs. Actual Behavior

It shouldn't close the keyboard if we press the arrows, and it should just close it if we press Done

### Contact Information

Dc: nyami11

**Comment by paulederbaus** [comment]
This bug will not be fixed because it's too much effort for a small enhancement.
