### ISSUE TITLE
use any ninebot battery!

### ISSUE THREAD

**Issue by NormalHuman-Anything** [scooterhacking/scooterhacking-issues-public#52]
### Scooterhacking Tool

Firmware (SHFW)

### Type of feature

Performance

### Priority

low (take your time)

### SHUT Version

rc v8

### SHFW Version

.3.8

### Scooter model

Ninebot Es2, Es3, Es4

### Description of the new feature

found out nb escs can communicate any ninebot bms, just doesnt read proper bms fw number but all data can be read like cycle life, cell voltages and etc. and even battery percentage!
so I thought, "the bms emu doesn't even work when error 49/50 is showing, so why not somehow trick the controller that right bms fw version is in and work around that 49/50 error code?"
enabling us to use "ANY" ninebot bms with comms!

**Comment by NormalHuman-Anything** [comment]
![Screenshot_20240303-023644_Scootbatt](https://github.com/scooterhacking/scooterhacking-issues-public/assets/72422431/7d238d14-44b3-4280-a45d-fd3063379283)

g30 batt with bms 1.3.4
esx with 0.3.8 shfw(Stat is kinda bugged cause I accidentally wiped the data area while flashing)

**Comment by paulederbaus** [comment]
Would it be sufficient to suppress error 49?

**Comment by NormalHuman-Anything** [comment]
yea more likely that
error 49&50 is the thing responsible for that so
suppressing that would be sufficient

**Comment by paulederbaus** [comment]
Error 49 and error 50 will be suppressed in the next version

**Comment by NormalHuman-Anything** [comment]
yep
