### ISSUE TITLE
BUG: overtemp error @72v after a while with no sensors

### ISSUE THREAD

**Issue by IAMFreehandZ** [scooterhacking/scooterhacking-issues-public#56]
### Scooterhacking Tool

Firmware (SHFW)

### Type of issue

Other

### Severity of issue

low (asthetic, minor issue)

### SHUT Version

rc_support_shfw_037_v8

### SHFW Version

SHFW 0.3.7 prerelease v8

### Scooter model

Ninebot G30

### Description of the Bug

I have 72v, and have modded the esc accordingly (270k adc resistor, 100v fets + caps). When riding, after ~10 minutes I get an overtemp error on the dashboard (the symbol flashing) however the BMS has no comms connected and the ESC afaik has no temp sensors. The casing of the ESC is also basically cool to the touch. To be clear, I am unsure if 72v is the issue however I run it. Happens randomly, and disappears randomly too after a while of not riding.

I also have a front esc but I have no idea if it does this.

My SHFW settings are:
20 amps DPC quadratic
1kph start speed
100% Acceleration boost
100% brake boost @ 15a reverse quadratic curve
Field Weakening
45 start speed
2a initial
1000mA variable
30a max torque current
20a max flux current
92.4v adc max voltage

I would prefer to discuss this on discord.

### Steps to Reproduce

1. Setup the scooter with 72v, no BMS comms connected and use 0.3.7 v8 prerelease, copy settings. 2. Ride at high speeds for 10 mins. 3. Get overtemp symbol flashing

### Expected vs. Actual Behavior

Expected is there should be no overtemp error as it is not over temp from what I can tell, as well as there being no temperature sensor.

What I get is an overtemp error after ~10 min.

### Contact Information

FreehandZ

**Comment by IAMFreehandZ** [comment]
Forgot to add this also happens with multiple different shfw configurations, with and without field weakening. Same 72v + esc modifications and 2 escs (dual motor).

**Comment by IAMFreehandZ** [comment]
Lekrsu confirmed fix works.

**Comment by paulederbaus** [comment]
> Lekrsu confirmed fix works.

Wasn't that solved now?

**Comment by IAMFreehandZ** [comment]
> > Lekrsu confirmed fix works.
> 
> Wasn't that solved now?
Yeah lekrsu told me he and you worked out a fix. I created this issue before lekrsu told me
