### ISSUE TITLE
Feature: Poweralgo (Delta)

### ISSUE THREAD

**Issue by Ben-Star-Delta** [scooterhacking/scooterhacking-issues-public#60]
### Scooterhacking Tool

Firmware (SHFW)

### Type of feature

Performance

### Priority

medium

### SHUT Version

2.3.0

### SHFW Version

0.3.7

### Scooter model

Ninebot G30

### Description of the new feature

Hello, i want to suggest something. In the old cfw times there was a Parameter, named "Virtual Throttle Limit". Anyways this parameter does something else than what it is named like. It has surely something to do with the poweralgo. I hope that there is a way to recreate this parameter in the Beta, but you have to rename it. The parameter helps to run the delta mod. It makes the motor pull more current. 

### Contact Information

14S (Discord)

**Comment by paulederbaus** [comment]
I don't see that parameter in a sh cfw generator. What generator did you use?

Was the default value 125, 128 or 183?

**Comment by Ben-Star-Delta** [comment]
It got removed from the CFW Tool of scooterhacking.

paulederbaus ***@***.***> schrieb am Fr., 12. Apr. 2024,
19:19:

**Comment by paulederbaus** [comment]
@nopbxlr Please help me. What was patched with this?

**Comment by Ben-Star-Delta** [comment]
I am generating my firmware through a Link because it is not possible to set the Parameter in the Firmware Generator of Scooterhacking. 
I just swap the last number of the link. Usually it is 120.

https://api.cfw.sh/max?output=zip2&version=DRV126&compat_patches=on&region=auto&remove_charging_mode=on&version_spoofing=on&showbatt=off&boot_workmode=3&voltage=36&p_sports=50000&p_drive=16000&i_sports=50000&i_drive=24000&i_eco=16000&max_speed_us=17&max_speed_eu=17&max_speed_de=17&direct_power_control=reg&direct_power_control_curve=quadratic&current_raising_coefficient=1000&motor_start_speed=1&brake_limit=130&brake_i_min=6000&brake_i_max=25000&kers_min_speed=5&no_kers=on&brake_current_raising_coefficient=500&brake_light_mode=static&brake_light_flash_frequency=0&cruise_control_delay=5&no_cruise_control=on&error_raising_level=3&no_overspeed_alarm=on&stay_on_locked=on&wheel_size=10.0&throttle_limit=97

**Comment by paulederbaus** [comment]
You are using a bug of an older patcher version. If you increase your total current limit, you will have the same effect in SHFW.

**Comment by Ben-Star-Delta** [comment]
Sorry but it doesnt have the same effect. I tested it a few times already:
CFW 97 Coeff 50A set Phase Current 
-----> ~65A Phase Current
SHFW 50A Phase Current 
-----> ~40A Phase Current 

But also:
CFW 97 Coeff 25A
----> ~36A Phase Current (fast acceleration)
SHFW 40A Phase Current
----> ~36A Phase Current (very slow acceleration)

Even though it is the same real Phase current, there is a huge difference in acceleration. 

And i also dont think that it is a bug, because this parameter has no real impact if you are running your motor in star, but if you run it in delta, it has a huge impact.


paulederbaus ***@***.***> schrieb am So., 28. Apr. 2024,
15:21:
