### ISSUE TITLE
BUG: Updating to 0.3.7

### ISSUE THREAD

**Issue by PureComedi** [scooterhacking/scooterhacking-issues-public#64]
### Scooterhacking Tool

Utility (SHUT)

### Type of issue

Performance issue

### Severity of issue

medium (affects usability but has a workaround)

### SHUT Version

2.4.0

### SHFW Version

0.3.7 

### Scooter model

All, from my observation

### Description of the Bug

The maximum field current setting or something else regarding field weakening gets messed up and either makes the scooter slower after updating from 0.3.6, or straight up makes it act as if field weakening is turned off

The workaround is resetting your shfw settings, sometimes updating the maximum field current setting works too, but not always 

### Steps to Reproduce

Update to 0.3.7 from 0.3.6
Try to drive 

### Expected vs. Actual Behavior

Scooter go zoom vs scooter no go zoom

### Contact Information

purecomedi

**Comment by SpookieGames** [comment]
Hey there, I have the same issue however resetting the settings doesn't help. Any ideas as to what to do next?

**Comment by IIlIIllll** [comment]
i have the issue, that FW doesnt work after Shfw and shu update. i try tmrw to reset all shfw settings. hope thats the solution

**Comment by paulederbaus** [comment]
This bug should be solved by updating to 3.7.1 - Please test and report back

**Comment by IIlIIllll** [comment]
jup läuft wiederlgDaniel KirchhoffAm 24/04/2024 um 10:15 schrieb paulederbaus ***@***.***>:﻿
This bug should be solved by updating to 3.7.1 - Please test and report back

**Comment by nopbxlr** [comment]
As this issue appears to be solved, it will be closed.
