### ISSUE TITLE
BUG: Error 19 out of nowhere on esx and E25

### ISSUE THREAD

**Issue by avg-nikki** [scooterhacking/scooterhacking-issues-public#65]
### Scooterhacking Tool

Firmware (SHFW)

### Type of issue

Other

### Severity of issue

medium (affects usability but has a workaround)

### SHUT Version

SHUT 2.4.1

### SHFW Version

SHFW 3.7.0

### Scooter model

Ninebot Es2, Es3, Es4

### Description of the Bug

(also present on E25) 
Errors 16 and 19 pop up with no reasoning behind them. Haven't seen this behavior myself on 0.3.6, 0.3.7 RC1, but can reproduce on release version. Multiple people are reporting issues of error 19 popping up after clean installing 3.7.0. 
![image](https://github.com/scooterhacking/scooterhacking-issues-public/assets/152761264/7c55869e-5b5a-43d2-929c-a8812baf0ed5)
![image](https://github.com/scooterhacking/scooterhacking-issues-public/assets/152761264/a8f3b3ac-47ee-453f-8a03-6e79d9f311fd)
![image](https://github.com/scooterhacking/scooterhacking-issues-public/assets/152761264/66efc16d-30aa-4ebc-8d4d-dfca5a563c33)
![image](https://github.com/scooterhacking/scooterhacking-issues-public/assets/152761264/1e9ed30b-9f52-41af-b92b-337424573bb9)

### Steps to Reproduce

1. Have an esx scooter
2. Install 3.7.0

### Expected vs. Actual Behavior

Expected: No error.
Actual: Yes error.

### Contact Information

@kittyle on Discord, @el_khatto on Telegram. Will update this issue if I find out anything else.

**Comment by avg-nikki** [comment]
thanks to @paulederbaus, seems to be fixed. will ride home today, update this issue, and we'll see how it goes.

![Screenshot_20240421-210130](https://github.com/scooterhacking/scooterhacking-issues-public/assets/152761264/52c5bb09-9f88-4f70-a145-60ca51fe382b)

**Comment by avg-nikki** [comment]
According to a person in [🇷🇺 Ninebot | Segway chat & forum (Telegram)](https://t.me/ninebot_by_segway/38728), installing base133 on esx drops error 16, and installing base255 drops error 19. Will check if I can reproduce that myself right now.

**Comment by avg-nikki** [comment]
> According to a person in [🇷🇺 Ninebot | Segway chat & forum (Telegram)](https://t.me/ninebot_by_segway/38728), installing base133 on esx drops error 16, and installing base255 drops error 19. Will check if I can reproduce that myself right now.

![image](https://github.com/scooterhacking/scooterhacking-issues-public/assets/152761264/b87fbe7a-f030-4aa6-a749-8e78312d5a47)

**Comment by avg-nikki** [comment]
Indeed, with 133, I get error 16, and with 255, I get error 19.
![Screenshot_20240422-010113](https://github.com/scooterhacking/scooterhacking-issues-public/assets/152761264/1ee89fe5-b5c0-4eb5-94ef-3e295658bcb5)
![Screenshot_20240422-010040](https://github.com/scooterhacking/scooterhacking-issues-public/assets/152761264/067de6b6-6124-46e2-b119-71c5468b2af4)

**Comment by avg-nikki** [comment]
@paulederbaus managed to fix it up!  
![image](https://github.com/scooterhacking/scooterhacking-issues-public/assets/152761264/72d1ec97-72d2-49c9-ad9f-bc9248dfc818)

**Comment by NormalHuman-Anything** [comment]
update fixes it

**Comment by avg-nikki** [comment]
> update fixes it

Sure does! 🎉 
Thanks, @paulederbaus!
![photo_2024-04-24_08-39-05](https://github.com/scooterhacking/scooterhacking-issues-public/assets/152761264/df9f8ed9-1a5c-40e6-a4e6-45dd0dde5cb8)
