### ISSUE TITLE
Feature: More Phase Options

### ISSUE THREAD

**Issue by Ben-Star-Delta** [scooterhacking/scooterhacking-issues-public#73]
### Scooterhacking Tool

Firmware (SHFW)

### Type of feature

Performance

### Priority

medium (upcoming releases)

### SHUT Version

2.5.1

### SHFW Version

0.3.7

### Scooter model

Ninebot G30

### Description of the new feature

Maybe you could add more advanced settings, like duty cycle.....and more.

### Contact Information

0.moon_light.

**Comment by PureComedi** [comment]
Are we going full VESC at this point..

**Comment by NormalHuman-Anything** [comment]
vesc moment

**Comment by paulederbaus** [comment]
This will be somehow added with next version (3.8.0).
