### ISSUE TITLE
adding sensorless control

### ISSUE THREAD

**Issue by NormalHuman-Anything** [scooterhacking/scooterhacking-issues-public#74]
### Scooterhacking Tool

Firmware (SHFW)

### Type of feature

UI / UX

### Priority

medium (upcoming releases)

### SHUT Version

2.5

### SHFW Version

3.7.1

### Scooter model

Ninebot G30

### Description of the new feature

sensorless control (in case like motor hall senor escapes its original position so it won't work , running some different motor with 120° hall sensor angle or etc)
would be a very good feature to have. had to walk home 10km because hall sensor decided to escape the position Caz glue got loose.
and also option to reverse the direction if it's spinning backwards or etc

### Contact Information

Jason on discord

**Comment by NormalHuman-Anything** [comment]
![Screenshot_20240502_191229.jpg](https://github.com/scooterhacking/scooterhacking-issues-public/assets/72422431/2dc9868a-9f98-41ed-af84-0ec847409272)

**Comment by paulederbaus** [comment]
This feature requires too many code changes to be implemented in a regular DRV. We know how different F-Series DRV is. Sorry but we won't be able to implement this.
