### ISSUE TITLE
Feature: Advanced Poweralgo

### ISSUE THREAD

**Issue by Ben-Star-Delta** [scooterhacking/scooterhacking-issues-public#78]
### Scooterhacking Tool

Firmware (SHFW)

### Type of feature

Performance

### Priority

low (take your time)

### SHUT Version

2.3.0

### SHFW Version

0.3.7

### Scooter model

Ninebot G30

### Description of the new feature

More Expert Options, to optimize the power algo of the motor. (useful if you dont use the stock motor or use delta motor)

### Contact Information

0.moon_light.

**Comment by IAMFreehandZ** [comment]
I think the motor algo in shfw is pretty much hard coded, so I think it'd be very time consuming for Paul to write a new algo for a very small group of people.

**Comment by paulederbaus** [comment]
Please explain what you have in mind and how it would change the scooter's behavior.
