### ISSUE TITLE
Feature: Restricted DRV version recognition

### ISSUE THREAD

**Issue by Nyami11** [scooterhacking/scooterhacking-issues-public#82]
### Scooterhacking Tool

Utility (SHUT)

### Type of feature

UI / UX

### Priority

medium (upcoming releases)

### SHUT Version

2.5

### SHFW Version

?

### Scooter model

Ninebot G30

### Description of the new feature

Give a popup in case the scooter runs a restricted DRV firmware that tells the user that he has to downgrade the ESC with an ST-Link, just like how it gives the restricted BLE warning on xiaomi scooters. It would also be great if it would give a different message in case the DRV version can be downgraded with the "Attempt DRV downgrade" function (for example on DRV 2.4.5 on xiaomi).

### Contact Information

dc: Nyami11

**Comment by nopbxlr** [comment]
We had such a filter before in older versions of the app, but I removed it as version spoofing and compat firmware make it unviable. There is currently no plan to add it back because of such limitations.
