### ISSUE TITLE
Motor start speed correction 

### ISSUE THREAD

**Issue by PureComedi** [scooterhacking/scooterhacking-issues-public#86]
### Scooterhacking Tool

Utility (SHUT)

### Type of feature

UI / UX

### Priority

low (take your time)

### SHUT Version

2.5.0

### SHFW Version

3.7.1

### Scooter model

(All scooters with -3 start) 

### Description of the new feature

Either preferably, 
change the "0" option on motor start speed to display -3 instead, or
add 0, then -3 as an option 

### Contact Information

purecomedi

**Comment by paulederbaus** [comment]
Implemented with rc4
