### ISSUE TITLE
Always on headlight not working

### ISSUE THREAD

**Issue by NormalHuman-Anything** [scooterhacking/scooterhacking-issues-public#88]
### Scooterhacking Tool

Firmware (SHFW)

### Type of issue

Other

### Severity of issue

low (asthetic, minor issue)

### SHUT Version

g2 

### SHFW Version

rc3

### Scooter model

Ninebot Es2, Es3, Es4

### Description of the Bug

always on headlight doesn't keep the headlight turned on

### Steps to Reproduce

turn on always on headlight
see

### Expected vs. Actual Behavior

ex : headlight doesn't turn off in any way
ac : it behaves like if always on headlight is off

### Contact Information

jason

**Comment by paulederbaus** [comment]
Fixed with rc4
