### ISSUE TITLE
BUG: doesn't connect to connect to Xiaomi mi pro4

### ISSUE THREAD

**Issue by Nakis122** [scooterhacking/scooterhacking-issues-public#90]
### Scooterhacking Tool

Utility (SHUT)

### Type of issue

Other

### Severity of issue

high (major functionality broken, no workaround)

### SHUT Version

Don't know

### SHFW Version

Don't know

### Scooter model

Xiaomi Pro, Pro2, 1s, essential, 3

### Description of the Bug

It doesn't connect to Xiaomi mi 4pro

### Steps to Reproduce

Just doesn't connect/Bluetooth doesn't connect 

### Expected vs. Actual Behavior

No results 

### Contact Information

nak_is  for discord

**Comment by lekrsu** [comment]
4 Pro is not supported nor is it in the supported model list when you open the app.

**Comment by Nakis122** [comment]
> 4 Pro is not supported nor is it in the supported model list when you open the app.

do you know any other apps that work with the mi 4 pro?

**Comment by Nyami11** [comment]
> do you know any other apps that work with the mi 4 pro?
>

There are no public tools for it, and probably never will be.
Close this issue please. If you have other questions, ask on the SH discord server

**Comment by Nakis122** [comment]
okay
